### ISSUE TITLE
Dutch_National__Flag Problem

### ISSUE THREAD

**Issue by kamalrt11** [sukritishah15/DS-Algo-Point#398] opened 2020-10-04 04:26 UTC
## 🚀 Dutch National Flag Problem

Algorithm to sort an array of 0's,1's and 2's.(Sort Colors by assigning numbers to it)

### Have you read the Contribution Guidelines?

Yes

## Pitch

It uses no extra space for sorting like in Merge Sort and Array is sorted in only One Traversal. It is an in-place algorithm.

**Comment by ShreyonSinha** [comment] 2020-10-04 08:09
Can I work in this issue ?

**Comment by ExpressHermes** [comment] 2020-10-05 12:57
I would like to work on this in C++ and Python.

**Comment by disha4u** [comment] 2020-10-06 04:55
I would like to work in python

**Comment by disha4u** [comment] 2020-10-06 04:56
this is duplicate of #282

**Comment by disha4u** [comment] 2020-10-06 04:56
please close this

**Closed** 2020-10-06 06:34 UTC
