### ISSUE TITLE
Greedy implementation of coin change problem

### ISSUE THREAD

**Issue by ameycodes** [sukritishah15/DS-Algo-Point#601] opened 2020-10-07 08:47 UTC
## 🚀 Feature

This is a greedy implementation of the coin change problem. Finding the minimum number of denominations required.

### Have you read the Contribution Guidelines?

Yes

## Pitch

Useful in competitive programming and understanding the greedy algorithm

**Comment by ameycodes** [comment] 2020-10-07 08:48
I would like to work on its C++ implementation

**Comment by ExpressHermes** [comment] 2020-10-07 09:16
Duplicate of #171

**Comment by ExpressHermes** [comment] 2020-10-07 09:19
Duplicate of #171

**Closed** 2020-10-07 09:19 UTC
